[package]
name = "aileron-server"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "aileron-server"
path = "src/main.rs"

[[bin]]
name = "toasty"
path = "src/bin/toasty.rs"

[dependencies]
argon2 = "0.5.3"
axum = "0.8.9"
toasty = { version = "0.7.0", default-features = false, features = ["jiff", "turso"] }
toasty-cli = "0.7.0"
toasty-driver-turso = "0.7.0"
tracing-subscriber = { version = "0.3.23", features = ["ansi", "env-filter", "json"] }
tracing = "0.1.44"
tower-http = { version = "0.7.0", features = ["trace"] }
jiff = "0.2.29"

anyhow = { workspace = true }
aileron-config = { workspace = true }
tokio = { workspace = true, features = ["net"] }
uuid = { workspace = true }
serde = { workspace = true }
pasetors = "0.7.8"
base64 = "0.22.1"
axum-extra = { version = "0.12.6", features = ["cookie"] }
time = "0.3.53"
serde_json = "1.0.150"
