[package]
name = "elevon-http"
version = "0.1.0"
edition = "2024"

[dependencies]
base64 = "0.23.1"
rand = "0.10.2"
sha2 = "0.11.0"
tracing-subscriber = { version = "0.3.23", features = ["ansi", "json", "env-filter"] }

anyhow.workspace = true
axum.workspace = true
serde.workspace = true
tracing.workspace = true
tracing-indicatif.workspace = true
toasty.workspace = true
tokio.workspace = true
