[workspace]
resolver = "3"
members = ["./crates/*"]

[workspace.dependencies]
anyhow = "1"
dotenvy = "0.15.7"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.52.3", features = ["rt-multi-thread"] }
uuid = { version = "1.23.4", features = ["v7"] }

aileron-config = { path = "./crates/aileron-config" }
