[workspace]
resolver = "3"
members = [
  "crates/elevon-agent",
  "crates/elevon-auth",
  "crates/elevon-cli",
  "crates/elevon-config",
  "crates/elevon-deploy",
  "crates/elevon-fs",
  "crates/elevon-proxy",
  "crates/elevon-server",
]

[workspace.dependencies]
async-trait = "0.1.91"
anyhow = "1"
axum = "0.8.9"
clap = { version = "4.6.2", features = ["color", "derive"] }
dotenvy = "0.15.7"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.151"
tokio = { version = "1.53.0", features = ["rt-multi-thread", "macros"] }
tower-http = { version = "0.7.0", features = ["trace"] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"]}
thiserror = "2.0.19"
uuid = { version = "1.24.0", features = ["v7"] }

elevon-auth = { path = "./crates/elevon-auth" }
elevon-config = { path = "./crates/elevon-config" }
elevon-fs = { path = "./crates/elevon-fs" }
