[package]
name = "elevon-deploy"
version = "0.1.0"
edition = "2024"

[dependencies]
shlex = "2.0.1"
bytesize = { version = "2.7.0", features = ["serde"] }
tar.workspace = true
ignore = "0.4.33"

anyhow.workspace = true
bollard.workspace = true
clap.workspace = true
futures-util.workspace = true
reqwest = { workspace = true, features = ["stream"] }
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-indicatif.workspace = true
tracing-subscriber.workspace = true

elevon-config.workspace = true
elevon-contracts.workspace = true
elevon-http.workspace = true
