[package]
name = "elevon-contracts"
version = "0.1.0"
edition = "2024"

[dependencies]
elevon-config.workspace = true

anyhow.workspace = true
bytes.workspace = true
bollard.workspace = true
futures-util.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
tracing.workspace = true
tracing-indicatif.workspace = true
