name: Release
description: Composite action for releasing builds

inputs:
  tag:
    description: Tag name
    required: true
  files:
    description: Release files
    required: true
    type: string

runs:
  using: composite
  steps:
    - name: Generate checksums
      shell: bash
      run: sha256sum ${{ inputs.files }} > SHA256SUMS

    - uses: softprops/action-gh-release@v3
      with:
        tag_name: ${{ inputs.tag }}
        name: ${{ inputs.tag }}
        generate_release_notes: true
        files: |
          ${{ inputs.files }}
          SHA256SUMS
