[package]
name = "elevon-agent"
version = "0.1.0-beta.2"
edition = "2024"
default-run = "elevon-agent"

[dependencies]
arc-swap = "1.9.2"
dashmap = "6.2.1"
tokio-stream = "0.1.19"
tabled = "0.22.0"

async-trait.workspace = true
anyhow.workspace = true
axum.workspace = true
bollard.workspace = true
bytes.workspace = true
clap.workspace = true
futures-util.workspace = true
jiff.workspace = true
pingora = { version = "0.9.0", features = ["lb", "proxy", "boringssl"] }
reqwest = { workspace = true, features = ["stream", "query"] }
serde.workspace = true
serde_json.workspace = true
strum.workspace = true
strum_macros.workspace = true
tokio = { workspace = true, features = ["net"] }
tokio-util = { workspace = true, features = ["codec"] }
tower-http.workspace = true
toasty = { workspace = true, features = ["migration"] }
toasty-cli.workspace = true
toasty-driver-turso = { workspace = true, features = ["sync"] }
tracing.workspace = true
uuid.workspace = true

elevon-config.workspace = true
elevon-contracts.workspace = true
elevon-fs = { workspace = true, features = ["agent"] }
elevon-http.workspace = true

