name: Release Deploy

on:
  push:
    tags: ["elevon-deploy-v*"]
  workflow_dispatch:
    inputs:
      version:
        description: "Version (e.g. 0.1.0)"
        required: true
        type: string

permissions:
  contents: write

jobs:
  build-linux:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.build.outputs.tag }}

    steps:
      - uses: actions/checkout@v7

      - uses: ./.github/actions/build-crate
        id: build
        with:
          name: elevon-deploy
          version: ${{ inputs.version }}
      
      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: elevon-deploy-linux
          path: ${{ steps.build.outputs.archive }}

  release:
    needs: [build-linux]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: actions/download-artifact@v8
        with:
          pattern: elevon-deploy-*
          merge-multiple: true
          path: dist

      - name: Debug downloaded artifacts
        run: |
          echo "== dist =="
          ls -la
          echo "== dist tree =="
          find dist -maxdepth 3 -type f -o -type d | sort

      - uses: ./.github/actions/releas1e-crate
        with:
          tag: ${{ needs.build-linux.outputs.tag }}
          files: dist/*.tar.gz
